ESMIlWebApp/Controllers/ProgrammeDataTableView/ProgrammeDataTableViewController.cs
using DataStructure.ViewModel;
using Infrastructure.Interface;
using Microsoft.AspNetCore.Mvc;

namespace ESMIlWebApp.Controllers.ProgrammeDataTableView
{
    public class ProgrammeDataTableViewController : Controller
    {
        private readonly IProgrammeTableRepository _programmeTableRepository;
        public ProgrammeDataTableViewController(IProgrammeTableRepository programmeTableRepository)
        {
            _programmeTableRepository = programmeTableRepository;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        [Route("New/Programme")]
        public IActionResult AddProgramme()=>View();

        [HttpGet]
        [Route("AllProgramme")]
        public IActionResult AllProgramme()=>View();
        [HttpGet]
        [Route("ViewOurProgramme")]
        public IActionResult OurProgramme() => View();

        [Route("Update/Programme")]
        public IActionResult UpdateProgramme() 
        {
            var model = new ProgrammeTableDTO();
            var rowId = Request.Form["updateRecordId"].FirstOrDefault();
            if (rowId ==null)
            {
                ViewBag.NoRecordFound = "No record found";
                return View();
            }
            var id = int.Parse(rowId);
            model=_programmeTableRepository.GetAllProgrammeTableAsync().Where(s=>s.Id==id).FirstOrDefault();

            return View(model);
        }

        public IActionResult ViewProgramme() 
        {
            var model= new ProgrammeTableDTO();
            var rowId = Request.Form["viewRecordId"].FirstOrDefault();
            if (rowId !=null)
            {
                var id= int.Parse(rowId);
                model=_programmeTableRepository.GetAllProgrammeTableAsync().Where(s=>s.Id==id).FirstOrDefault();
            }
            return View(model);
        }
    }
}

ESMIlWebApp/Views/ProgrammeDataTableView/AddProgramme.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h5 class="text-muted">Add Programme</h5>
<div class="container" style="background-color:lightblue">
    <form id="clearFrm">
        <div class="row">
            <div class="col-4">
                <div class="form-group required">
                    <label class="form-label">Speaker</label>
                    <input id="rowId" type="hidden">
                    <input class="form-control" id="txtSpeaker" type="text" placeholder="">
                </div>

            </div>
            <div class="col-4">
                <div class="form-group required">
                    <label class="form-label">Cordinator</label>
                    <input class="form-control" id="txtCordinator" type="text" placeholder="">
                </div>
            </div>
            <div class="col-4">
                <div class="form-group required">
                    <label class="form-label">Programme</label>
                    <input class="form-control" id="txtProgramme" type="text" placeholder="">
                </div>
            </div>
        </div>
        <br />
        <br>

        <div class="row">
            <div class="col-lg-4">
                <div class="form-group mg-b-10-force required">
                    <label for="">Programme Date </label>
                    <div class="ate-input">
                        <div class="ate-input">
                            <input type="text" class="date form-control" placeholder="Date" id="txtProgrammeDate">
                        </div>
                    </div>
                </div>
            </div><!-- col-4 -->
            <div class="col-4">
                <div class="form-group">
                    <label class="form-label">Note</label>
                    <input class="form-control" id="txtNote" type="text" placeholder="">
                </div>
            </div>
            <br />
            <div class="col-4">
                <div class="form-group required">
                    <label class="form-label">Status</label>
                    <div id="warning" height> </div>
                        <vc:programme-status></vc:programme-status>
                </div>
            </div>
            <br />
        </div>
        
        <div class="text-center">
            <br />
            <button class="btn btn-primary" type="submit" id="saveRecord">Save</button>
        </div>
    </form>
</div>

@section scripts{

    <script>

        var saveUrl = "@Url.Action("AddOrUpdateProgrammeData","ProgrammeTableData")";
        $.fn.clearForm = function () {
            this.each(function () { this.reset(); })
        }
        $("#saveRecord").click(function (e) {
            e.preventDefault();

            if ($("#drpProgrammeStatus").val() == "Select status") {
                Swal.fire('Please select a value.', '', 'warning');
                $("#warning").css({'background-color': 'orange', 'height': '7px', 'width': '100%' });
                return;
            }
            else{
                $("#warning").css({ 'background-color': '', 'height': '', 'width': '' });
            }
            if (!$("#txtProgrammeDate").val()) {
                Swal.fire('Please select a date.', '', 'warning');
                $("#txtProgrammeDate").css({ 'background-color': 'orange' });
                return;
            }
            else {
                $("#txtProgrammeDate").css({ 'background-color': '' });
            }
            if (!$("#txtSpeaker").val()) {
                Swal.fire('Please input a value.', '', 'warning');
                $("#txtSpeaker").css({ 'background-color': 'orange' });
                return;
            }
            else {
                $("#txtSpeaker").css({ 'background-color': '' });
            }
            if (!$("#txtProgramme").val()) {
                Swal.fire('Please input a value.', '', 'warning');
                $("#txtProgramme").css({ 'background-color': 'orange' });
                return;
            }
            else {
                $("#txtProgramme").css({ 'background-color': '' });
            }
            if (!$("#txtCordinator").val()) {
                Swal.fire('Please input a value.', '', 'warning');
                $("#txtCordinator").css({ 'background-color': 'orange' });
                return;
            }
            else {
                $("#txtCordinator").css({ 'background-color': '' });
            }
            var body = {
                Id: $("#rowId").val() == "" ? 0 : $.trim($("#rowId").val()),
                Speaker: $.trim($("#txtSpeaker").val()),
                Cordinator: $.trim($("#txtCordinator").val()),
                Programme: $.trim($("#txtProgramme").val()),
                Note: $.trim($("#txtNote").val()),
                ProgrammeDate: $.trim($("#txtProgrammeDate").val()),
                ProgrammeStatus:$("#drpProgrammeStatus").val()
            }

            $.ajax({
                type: "POST",
                url: "@Url.Action("AddOrUpdateProgrammeData","ProgrammeTableData")",
                dataType: "Json",
                data: { payload: JSON.stringify(body) },
                success: function (response) {
                    if(response.hasError == false) {
                        Swal.fire(response.message, '', 'success');
                        $("#clearFrm").clearForm();
                    }
                    else if(response.hasError == true) {
                        Swal.fire(response.message, '', 'error');
                    }
                },

            });
        });
        jQuery('.date').datepicker({
            timepicker: false,
            format: 'Y/d/m',
        });

    </script>
}

ESMIlWebApp/Views/ProgrammeDataTableView/AllProgramme.cshtml
@{
    ViewData["Title"] = "Our Programme";
    Layout = "~/Views/Shared/_layout.cshtml";
}

<style>

</style>

<button class="btn btn-primary btn-rounded" id="newRecord">Add Programme</button>
<br>
<br>
<div class="table-responsive">
    @*<div style="overflow-x:scroll">*@
    <table id="programmeDataTable" width="100%" class="stripe hover">
        <thead>
            <tr>
                @* <th class="check-col" align="center"><input type="checkbox" name=selectAll value="1" id="example-select-all"></th>*@
                <th>Actions</th>
                <th>ID</th>
                <th>Speaker</th>
                <th>Cordinator</th>
                <th>Programme</th>
                <th>Programme Date </th>
                <th>Note</th>
                <th>Status</th>
             </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    @*</div>*@
</div>



@using (Html.BeginForm("ViewProgramme", "ProgrammeDataTableView", FormMethod.Post, new { id = "viewProgrammeDataForm", target = "_blank" }))
{
    <input type="hidden" name="viewRecordId" id="viewRecordId">
}
@using (Html.BeginForm("UpdateProgramme", "ProgrammeDataTableView", FormMethod.Post, new { id = "updateProgrammeDataForm", target = "_blank" }))
{
    <input type="hidden" name="updateRecordId" id="updateRecordId">
}


@section scripts{
    <script>

        var table = $("#programmeDataTable").DataTable({
            //columnDefs: [{
            //    targets: [12, 13],
            //    render: $.fn.dataTable.render.ellipsis(10)
            //}],
            "lengthMenu": [[7, 20, 25, 50, -1], [7, 20, 25, 50, "All"]],
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "paginate": true,
            "scrollX": true,
            // colReorder: false,
            //  rowReorder:false,
            //select: true,
            //dom: 'Bfrtip', , new{area="Unit"}
            "ajax": {
                "url": "@Url.Action("GetAllProgrammeData","ProgrammeTableData")",
                "type": "POST",
                "datatype": "json",
                "data": function (arg) { }
            },
            "columns": [
                {
                    "data": null, "name": "Action", "defaultContent": '<div class="btn-group mr-1 mb-1">' +
                        "<button aria-expanded='false' aria-haspopup='true' class='btn btn-white dropdown-toggle' data-toggle='dropdown' id='dropdownMenuDetail' type='button'></button>" +
                        "<div aria-labelledby='dropdownMenuButton6' class='dropdown-menu'>" +
                        "<a class='dropdown-item' href='#' id='changeRecord' title='Update record'><i class='fa fa-edit'></i>&nbsp; Update record</a>" +
                        "<a class='dropdown-item' href='#' id='viewRecord' title='View record'><i class='fa fa-info-circle'></i>&nbsp; View record</a>" +
                        "</div>" +
                        '</div>'

                },

                { "data": "id", "name": "id", "autoWidth": false },
                { "data": "speaker", "name": "speaker", "autoWidth": false },
                { "data": "cordinator", "name": "cordinator", "autoWidth": false },
                { "data": "programme", "name": "programme", "autoWidth": false },
                { "data": "strDate", "name": "programmeDate", "autoWidth": false },
                { "data": "note", "name": "note", "autoWidth": false },
                { "data": "programmeStatus", "name": "programmeStatus", "autoWidth": false },
            ],

        });




        $('#programmeDataTable tbody').on('click', '#viewRecord', function (e) {
            e.preventDefault();
            var data = table.row($(this).parents('tr')).data();
            $("#viewRecordId").val(data.id);
            $("#viewProgrammeDataForm").submit();

        });

        $('#programmeDataTable tbody').on('click', '#changeRecord', function (e) {
            e.preventDefault();
            var data = table.row($(this).parents('tr')).data();
            $("#updateRecordId").val(data.id);
            $("#updateProgrammeDataForm").submit();

        });

        $('#newRecord').on('click', function (e) {
            e.preventDefault();
            var returnUrl = '@Url.Action("AddProgramme", "ProgrammeDataTableView")';
            window.location.href = returnUrl;
        })

    </script>
}

ESMIlWebApp/Views/ProgrammeDataTableView/OurProgramme.cshtml
@{
    ViewData["Title"] = "Our Programme";
    Layout = "~/Views/Shared/_layout.cshtml";
}

<style>

</style>


<br>
<div class="table-responsive">
    @*<div style="overflow-x:scroll">*@
    <table id="programmeDataTable" width="100%" class="stripe hover">
        <thead>
            <tr>
                
                <th>Speaker</th>
                <th>Cordinator</th>
                <th>Programme</th>
                <th>Programme Date </th>
                <th>Note</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    @*</div>*@
</div>



@section scripts{
    <script>

        var table = $("#programmeDataTable").DataTable({
            //columnDefs: [{
            //    targets: [12, 13],
            //    render: $.fn.dataTable.render.ellipsis(10)
            //}],
            "lengthMenu": [[7, 20, 25, 50, -1], [7, 20, 25, 50, "All"]],
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "paginate": true,
            "scrollX": true,
            // colReorder: false,
            //  rowReorder:false,
            //select: true,
            //dom: 'Bfrtip', , new{area="Unit"}
            "ajax": {
                "url": "@Url.Action("GetAllProgrammeData","ProgrammeTableData")",
                "type": "POST",
                "datatype": "json",
                "data": function (arg) { }
            },
            "columns": [
                
                { "data": "speaker", "name": "speaker", "autoWidth": false },
                { "data": "cordinator", "name": "cordinator", "autoWidth": false },
                { "data": "programme", "name": "programme", "autoWidth": false },
                { "data": "strDate", "name": "programmeDate", "autoWidth": false },
                { "data": "note", "name": "note", "autoWidth": false },
                { "data": "programmeStatus", "name": "programmeStatus", "autoWidth": false },
            ],

        });

    </script>
}

ESMIlWebApp/Views/ProgrammeDataTableView/UpdateProgramme.cshtml
@model DataStructure.ViewModel.ProgrammeTableDTO
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h5 class="text-muted">Update Programme</h5>
<div class="container" style="background-color:lightblue">
    <form id="clearFrm">
        <div class="row">
            <div class="col-4">
                <div class="form-group">
                    <label class="form-label">Speaker</label>
                    <input id="rowId" value="@Model.Id" type="hidden">
                    <input class="form-control" id="txtSpeaker" value="@Model.Speaker" type="text" placeholder="">
                </div>

            </div>
            <div class="col-4">
                <div class="form-group">
                    <label class="form-label">Cordinator</label>
                    <input class="form-control" id="txtCordinator" value="@Model.Cordinator" type="text" placeholder="">
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label class="form-label">Programme</label>
                    <input class="form-control" id="txtProgramme" value="@Model.Programme" type="text" placeholder="">
                </div>
            </div>
        </div>
        <br />
        <br>

        <div class="row">
            <div class="col-lg-4">
                <div class="form-group mg-b-10-force">
                    <label for="">Programme Date </label>
                    <div class="ate-input">
                        <div class="ate-input">
                            <input type="text" class="date form-control" placeholder="Date" value="@Model.strDate" id="txtProgrammeDate">
                        </div>
                    </div>
                </div>
            </div><!-- col-4 -->
            <div class="col-4">
                <div class="form-group">
                    <label class="form-label">Note</label>
                    <input class="form-control" id="txtNote" type="text" value="@Model.Note" placeholder="">
                </div>
            </div>
            <br />
            <div class="col-4">
                <div class="form-group">
                    <label class="form-label">Status</label>
                    <vc:programme-status></vc:programme-status>
                </div>
            </div>
            <br />
        </div>

        <div class="text-center">
            <br />
            <button class="btn btn-primary" type="submit" id="saveRecord">Save</button>
        </div>
    </form>
</div>

@section scripts{

    <script>

        var saveUrl = "@Url.Action("AddOrUpdateProgrammeData","ProgrammeTableData")";
        $.fn.clearForm = function () {
            this.each(function () { this.reset(); })
        }
        $("#saveRecord").click(function (e) {
            e.preventDefault();

            var body = {
                Id: $("#rowId").val() == "" ? 0 : $.trim($("#rowId").val()),
                Speaker: $.trim($("#txtSpeaker").val()),
                Cordinator: $.trim($("#txtCordinator").val()),
                Programme: $.trim($("#txtProgramme").val()),
                Note: $.trim($("#txtNote").val()),
                ProgrammeDate: $.trim($("#txtProgrammeDate").val()),
                ProgrammeStatus: $("#drpProgrammeStatus").val()
            }

            $.ajax({
                type: "POST",
                url: "@Url.Action("AddOrUpdateProgrammeData","ProgrammeTableData")",
                dataType: "Json",
                data: { payload: JSON.stringify(body) },
                success: function (response) {
                    if (response.hasError == false) {
                        Swal.fire(response.message, '', 'success');
                        $("#clearFrm").clearForm();
                    }
                    else if (response.hasError == true) {
                        Swal.fire(response.message, '', 'error');
                    }

                },

            });
        });
        jQuery('.date').datepicker({
            timepicker: false,
            format: 'Y/d/m',
        });

    </script>
}

ESMIlWebApp/Views/ProgrammeDataTableView/ViewProgramme.cshtml
@model DataStructure.ViewModel.ProgrammeTableDTO
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h5 class="text-muted">Add Programme</h5>
<div class="container" style="background-color:lightblue">
    <form id="clearFrm">
        <div class="row">
            <div class="col-4">
                <div class="form-group">
                    <label class="form-label">Speaker</label>
                    <input id="rowId" type="hidden">
                    <input class="form-control" id="txtSpeaker" type="text" value="@Model.Speaker" readonly placeholder="">
                </div>

            </div>
            <div class="col-4">
                <div class="form-group">
                    <label class="form-label">Cordinator</label>
                    <input class="form-control" id="txtCordinator" type="text" value="@Model.Cordinator" readonly placeholder="">
                </div>
            </div>
            <div class="col-4">
                <div class="form-group">
                    <label class="form-label">Programme</label>
                    <input class="form-control" id="txtProgramme" type="text" value="@Model.Programme" readonly placeholder="">
                </div>
            </div>
        </div>
        <br />
        <br>

        <div class="row">
            <div class="col-lg-4">
                <div class="form-group mg-b-10-force">
                    <label for="">Programme Date </label>
                    <div class="ate-input">
                        <div class="ate-input">
                            <input type="text" class="date form-control" placeholder="Date" value="@Model.strDate" id="txtProgrammeDate">
                        </div>
                    </div>
                </div>
            </div><!-- col-4 -->
            <div class="col-4">
                <div class="form-group">
                    <label class="form-label">Note</label>
                    <input class="form-control" id="txtNote" value="@Model.Note" type="text" placeholder="">
                </div>
            </div>
            <br />
            <div class="col-4">
                <div class="form-group">
                    <label class="form-label">Status</label>
                    <vc:programme-status></vc:programme-status>
                </div>
            </div>
            <br />
        </div>

        <div class="text-center">
            <br />
            <button class="btn btn-primary" type="submit" id="saveRecord">Save</button>
        </div>
    </form>
</div>

@section scripts{

    <script>

        $(document).ready(function () {
            $("#drpProgrammeStatus").val('@Model.ProgrammeStatus').trigger('change');
        });
    
    </script>
}