ESMIlWebApp/Controllers/FloorMember/GeneralMemberController.cs
using DataStructure.ViewModel;
using ESMIlWebApp.Ultilities;
using Infrastructure.Interface;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Data.Entity;
using System.Net;

namespace ESMIlWebApp.Controllers.ESMAF
{
    public class GeneralMemberController : Controller
    {
        private readonly IGeneralMemberRepository _generalMemberRepository;
        private readonly ILogger<GeneralMemberController> _logger;
        string errorMessage = string.Empty;
        public GeneralMemberController(ILogger<GeneralMemberController> logger, IGeneralMemberRepository generalMemberRepository)
        {
            _generalMemberRepository = generalMemberRepository;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> AddOrUpdateGeneralMember(string payload)
        {

            try
            {
                if (payload != null)
                    //payload = EncryptionExtensions.EncryptStringAES(payload);
                 payload = EncryptionExtensions.DecryptStringAES(payload);
                var model = JsonConvert.DeserializeObject<GeneralMemberData>(payload);

                var saveEsmaf = await _generalMemberRepository.AddOrUpdateGeneralMember(model);
                if (model.Id > 0)
                {
                    return Json(new ResponseModel { message = $"{model.Surname}'s record successfully updated ", hasError = false, statusCode = (int)HttpStatusCode.OK });
                }
                return Json(new ResponseModel { message = $"{model.Surname} has been added successfully", hasError = false, statusCode = (int)HttpStatusCode.OK });
            }
            catch (Exception e)
            {

                _logger.LogError("Error", e);
                errorMessage = e.Message;
            }
            return Json(new ResponseModel { message = $"Error Message {Environment.NewLine}{errorMessage}", hasError = true, statusCode = (int)HttpStatusCode.BadRequest });
        }

        public IActionResult GetAllGeneralMember()
        {
            string errorMessage;
            try
            {
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();
                //switch (length)
                //{
                //    case "oyo":
                //        _generalMemberRepository.ListAllGeneralMember();
                //         break;
                //    case "Ondo":
                //    default:
                //     break;
                //}
                var search = Request.Form["search[value]"].FirstOrDefault();

                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int totalRecord = 0;

                var generalMemberRecord = _generalMemberRepository.ListAllGeneralMember().ToList();

                if (!string.IsNullOrWhiteSpace(search.ToString()))
                {
                    generalMemberRecord = generalMemberRecord.Where(s =>s.Surname.ToLower().Contains(search)
                      || s.Firstname.ToLower().Contains(search)
                      || s.Othername.ToLower().Contains(search)
                      || s.PhoneNumber.ToLower().Contains(search)
                      || s.strYearJoinESM.ToLower().Contains(search)
                      || s.strYearOfEntry.ToLower().Contains(search)
                      || s.strYOG.ToLower().Contains(search)
                      || s.strDateOfBirth.ToLower().Contains(search)
                      || s.Gender.ToLower().Contains(search)
                      || s.HostelAddress.ToLower().Contains(search)
                      || s.SocialMediaAddress.ToLower().Contains(search)
                      ||s.LGA.ToLower().Contains(search)
                      || s.StateOfOrigin.ToLower().Contains(search)
                      || s.HouseAddress.ToLower().Contains(search)
                      || s.Email.ToLower().Contains(search)
                      || s.Faculty.ToLower().Contains(search)
                      || s.CourseOfStudy.ToLower().Contains(search)).ToList();
                }
                totalRecord = generalMemberRecord.Count();
                generalMemberRecord = generalMemberRecord.OrderByDescending(s => s.Id).ToList();
                if (pageSize != -1)
                {
                    generalMemberRecord = generalMemberRecord.OrderByDescending(s => s.Id).Skip(skip).Take(pageSize).ToList();
                }
                return Json(new
                {
                    draw,
                    recordsFiltered = totalRecord,
                    recordsTotal = totalRecord,
                    data = generalMemberRecord
                });

            }
            catch (Exception e)
            {
                _logger.LogError("Error", e.Message);
                errorMessage = e.Message;
            }
            return Json(new ResponseModel {hasError = true, message = $" Error:\a {errorMessage}" });


        }

        
    }
}

ESMIlWebApp/Controllers/FloorMember/GeneralMemberDataViewController.cs
using DataStructure.ViewModel;
using Infrastructure.Interface;
using Infrastructure.Service;
using Microsoft.AspNetCore.Mvc;

namespace ESMIlWebApp.Controllers.Testimony
{
    public class GeneralMemberDataViewController : Controller
    {
        private readonly IGeneralMemberRepository _generalMemberRepository;

        public GeneralMemberDataViewController(IGeneralMemberRepository generalMemberRepository) 
        {
        this._generalMemberRepository = generalMemberRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        [Route("All/GeneralMember")]
        public IActionResult AllGeneralMember() => View();
        [HttpGet]
        [Route("GeneralMember")]
        public IActionResult GeneralMember() => View();
        [HttpGet]
        [Route("New/GeneralMember")]
        public IActionResult CreateGeneralMember() => View();

        [Route("Update/GeneralMember/Data")]
        public IActionResult UpdateGeneralMember()
        {
            var model = new GeneralMemberDTO();
            var rowId = Request.Form["updateRecordId"].FirstOrDefault();
            if (rowId == null)
            {
                ViewBag.NoRecordFound = "No Record Found.";
                return View();
            }
            var id = int.Parse(rowId);
            model = _generalMemberRepository.ListAllGeneralMember().Where(s => s.Id == id).FirstOrDefault();
            return View(model);
        }

        [Route("View/GeneralMember/Data")]
        public IActionResult ViewGeneralMember()
        {
            var model = new GeneralMemberDTO();
            var rowId = Request.Form["viewRecordId"].FirstOrDefault();
            if (rowId == null)
            {
                ViewBag.NoRecordFound = "No Record Found.";
                return View();
            }
            var id = int.Parse(rowId);
            model = _generalMemberRepository.ListAllGeneralMember().Where(s => s.Id == id).FirstOrDefault();
            return View(model);
        }
    }
}

ESMIlWebApp/Views/GeneralMemberDataView/AllGeneralMember.cshtml
@{
    ViewData["Title"] = "General Member";
    Layout = "~/Views/Shared/_layout.cshtml";
}

<style>

</style>

<button class="btn btn-primary btn-rounded" id="newRecord">Capture New Record</button>
<br>
<br>
<div class="table-responsive">
    @*<div style="overflow-x:scroll">*@
    <table id="generalMemberTable" width="100%" class="stripe hover">
        <thead>
            <tr>
                @* <th class="check-col" align="center"><input type="checkbox" name=selectAll value="1" id="example-select-all"></th>*@
                <th>Actions</th>
                <th>Surname</th>
                <th>Firstname</th>
                <th>Othername</th>
                <th>Gender</th>
                <th>State Of Origin</th>
                <th>LGA</th>
                <th>Phone Number </th>
                <th>Email </th>
                <th>Department</th>
                <th>Faculty</th>
                <th>Ambition</th>
                <th>Hostel Address</th>
                <th>Home Address</th>
                <th>Social Media Address</th>
                <th>Date Join ESM</th>
                <th>Year of Entry</th>
                <th>Year of Graduation</th>
                <th>Date Of Birth</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    @*</div>*@
</div>



@using (Html.BeginForm("ViewGeneralMember", "GeneralMemberDataView", FormMethod.Post, new { id = "viewGeneralMemberForm", target = "_blank" }))
{
    <input type="hidden" name="viewRecordId" id="viewRecordId">
}
@using (Html.BeginForm("UpdateGeneralMember", "GeneralMemberDataView", FormMethod.Post, new { id = "updateGeneralMemberForm", target = "_blank" }))
{
    <input type="hidden" name="updateRecordId" id="updateRecordId">
}


@section scripts{
    <script>

        var table = $("#generalMemberTable").DataTable({
            columnDefs: [{
                targets: [12, 13],
                render: $.fn.dataTable.render.ellipsis(16)
            }],
            "lengthMenu": [[7, 20, 25, 50, -1], [7, 20, 25, 50, "All"]],
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "paginate": true,
            "scrollX": true,
            // colReorder: false,
            //  rowReorder:false,
            //select: true,
            //dom: 'Bfrtip', , new{area="Unit"}
            "ajax": {
                "url": "@Url.Action("GetAllGeneralMember","GeneralMember")",
                "type": "POST",
                "datatype": "json",
                "data": function (arg) { }
            },
            "columns": [
                {
                    "data": null, "name": "Action", "defaultContent": '<div class="btn-group mr-1 mb-1">' +
                        "<button aria-expanded='false' aria-haspopup='true' class='btn btn-white dropdown-toggle' data-toggle='dropdown' id='dropdownMenuDetail' type='button'></button>" +
                        "<div aria-labelledby='dropdownMenuButton6' class='dropdown-menu'>" +
                        "<a class='dropdown-item' href='#' id='changeRecord' title='Update record'><i class='fa fa-edit'></i>&nbsp; Update record</a>" +
                        "<a class='dropdown-item' href='#' id='viewRecord' title='View record'><i class='fa fa-info-circle'></i>&nbsp; View record</a>" +
                        "</div>" +
                        '</div>'

                },

                { "data": "surname", "name": "surname", "autoWidth": false },
                { "data": "firstname", "name": "firstname", "autoWidth": false },
                { "data": "othername", "name": "othername", "autoWidth": false },
                { "data": "gender", "name": "gender", "autoWidth": false },
                { "data": "stateOfOrigin", "name": "stateOfOrigin", "autoWidth": false },
                { "data": "lga", "name": "lga", "autoWidth": false },
                { "data": "phoneNumber", "name": "phoneNumber", "autoWidth": false },
                { "data": "email", "name": "email", "autoWidth": false },
                { "data": "courseOfStudy", "name": "courseOfStudy", "autoWidth": false },
                { "data": "faculty", "name": "faculty", "autoWidth": false },
                { "data": "ambition", "name": "ambition", "autoWidth": false },
                { "data": "hostelAddress", "name": "hostelAddress", "autoWidth": false },
                { "data": "houseAddress", "name": "houseAddress", "autoWidth": false },
                { "data": "socialMediaAddress", "name": "socialMediaAddress", "autoWidth": false },
                { "data": "strYearJoinESM", "name": "strYearJoinESM", "autoWidth": false },
                { "data": "strYearOfEntry", "name": "strYearOfEntry", "autoWidth": false },
                { "data": "strYOG", "name": "strYOG", "autoWidth": false },
                { "data": "strDateOfBirth", "name": "strDateOfBirth", "autoWidth": false }

            ],

        });

        $('#generalMemberTable tbody').on('click', '#viewRecord', function (e) {
            e.preventDefault();
            var data = table.row($(this).parents('tr')).data();
            $("#viewRecordId").val(data.id);
            $("#viewGeneralMemberForm").submit();

        });

        $('#generalMemberTable tbody').on('click', '#changeRecord', function (e) {
            e.preventDefault();
            var data = table.row($(this).parents('tr')).data();
            $("#updateRecordId").val(data.id);
            $("#updateGeneralMemberForm").submit();

        });

        $('#newRecord').on('click', function (e) {
            e.preventDefault();
            var returnUrl = '@Url.Action("CreateGeneralMember", "GeneralMember")';
            window.location.href = returnUrl;
        });

    </script>
   }

ESMIlWebApp/Views/GeneralMemberDataView/GeneralMember.cshtml
@{
    ViewData["Title"] = "General Member";
    Layout = "~/Views/Shared/_layout.cshtml";
}

<br>
<div class="table-responsive">
    @*<div style="overflow-x:scroll">*@
    <table id="generalMemberTable" width="100%" class="stripe hover">
        <thead>
            <tr>
                @* <th class="check-col" align="center"><input type="checkbox" name=selectAll value="1" id="example-select-all"></th>*@
                <th>Action</th>
                <th>Surname</th>
                <th>Firstname</th>
                <th>Gender</th>
                <th>State Of Origin</th>
                <th>Phone Number </th>
                <th>Department</th>
                <th>Faculty</th>
                <th>Ambition</th>
                <th>Hostel Address</th>
                <th>Social Media Address</th>
                <th>Date Join ESM</th>
                <th>Year of Entry</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
    @*</div>*@
</div>



@using (Html.BeginForm("ViewGeneralMember", "GeneralMemberDataView", FormMethod.Post, new { id = "viewGeneralMemberForm", target = "_blank" }))
{
    <input type="hidden" name="viewRecordId" id="viewRecordId">
}
@using (Html.BeginForm("UpdateGeneralMember", "GeneralMemberDataView", FormMethod.Post, new { id = "updateGeneralMemberForm", target = "_blank" }))
{
    <input type="hidden" name="updateRecordId" id="updateRecordId">
}


@section scripts{
    <script>

        var table = $("#generalMemberTable").DataTable({
            columnDefs: [{
                targets: [9],
                render: $.fn.dataTable.render.ellipsis(16)
            }],
            "lengthMenu": [[7, 20, 25, 50, -1], [7, 20, 25, 50, "All"]],
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "paginate": true,
            "scrollX": true,
            // colReorder: false,
            //  rowReorder:false,
            //select: true,
            //dom: 'Bfrtip', , new{area="Unit"}
            "ajax": {
                "url": "@Url.Action("GetAllGeneralMember","GeneralMember")",
                "type": "POST",
                "datatype": "json",
                "data": function (arg) { }
            },
            "columns": [
                {
                    "data": null, "name": "Action", "defaultContent": '<div class="btn-group mr-1 mb-1">' +
                        "<button aria-expanded='false' aria-haspopup='true' class='btn btn-white dropdown-toggle' data-toggle='dropdown' id='dropdownMenuDetail' type='button'></button>" +
                        "<div aria-labelledby='dropdownMenuButton6' class='dropdown-menu'>" +
                        "<a class='dropdown-item' href='#' id='viewRecord' title='View record'><i class='fa fa-info-circle'></i>&nbsp; View record</a>" +
                        "</div>" +
                        '</div>'

                },

                { "data": "surname", "name": "surname", "autoWidth": false },
                { "data": "firstname", "name": "firstname", "autoWidth": false },
                { "data": "gender", "name": "gender", "autoWidth": false },
                { "data": "stateOfOrigin", "name": "stateOfOrigin", "autoWidth": false },
                { "data": "phoneNumber", "name": "phoneNumber", "autoWidth": false },
                { "data": "courseOfStudy", "name": "courseOfStudy", "autoWidth": false },
                { "data": "faculty", "name": "faculty", "autoWidth": false },
                { "data": "ambition", "name": "ambition", "autoWidth": false },
                { "data": "hostelAddress", "name": "hostelAddress", "autoWidth": false },
                { "data": "socialMediaAddress", "name": "socialMediaAddress", "autoWidth": false },
                { "data": "strYearJoinESM", "name": "strYearJoinESM", "autoWidth": false },
                { "data": "strYearOfEntry", "name": "strYearOfEntry", "autoWidth": false }

            ],

        });




        $('#generalMemberTable tbody').on('click', '#viewRecord', function (e) {
            e.preventDefault();
            var data = table.row($(this).parents('tr')).data();
            $("#viewRecordId").val(data.id);
            $("#viewGeneralMemberForm").submit();

        });

    </script>
   }

ESMIlWebApp/Views/GeneralMemberDataView/ViewGeneralMember.cshtml
@model DataStructure.ViewModel.GeneralMemberDTO
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4 class="text-muted">General Member View Page</h4>

<br />
<div class="container hideForm" style="background-color:lightblue">
    <h5 class="text-primary">Capture new record</h5>
    <div class="row">
        <form id="clearFrm">
            <div class="row">
                <div class="col-4">
                    <div class="form-group">
                        <label class="form-label">Surname</label>
                        <input id="rowId" type="hidden" readonly value="@Model.Id">
                        <input class="form-control" id="txtSurname" readonly value="@Model.Surname" type="text" placeholder="">
                    </div>

                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label class="form-label">Firstname</label>
                        <input class="form-control" id="txtFirstname" type="text" readonly value="@Model.Firstname" placeholder="">
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label class="form-label">Otherename</label>
                        <input class="form-control" id="txtOthername" type="text" readonly value="@Model.Othername" placeholder="">
                    </div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group mg-b-10-force">
                        <label class="form-control-label">Gender</label>
                        <vc:gender></vc:gender>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group mg-b-10-force">
                        <label for="">Phone Number</label>
                        <div class="">
                            <div class="">
                                <input type="text" class="form-control" placeholder="" readonly value="@Model.PhoneNumber" id="txtPhoneNumber">
                            </div>
                        </div>
                    </div>
                </div><!-- col-4 -->
                <div class="col-4">
                    <div class="form-group">
                        <label class="form-label">Email</label>
                        <input class="form-control" id="txtEmail" type="text" value="@Model.Email" readonly placeholder="">
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group mg-b-10-force">
                        <label class="form-control-label">State of origin</label>
                        <vc:state></vc:state>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group mg-b-10-force">
                        <label class="form-control-label">LGA</label>
                        <vc:lga></vc:lga>
                    </div>
                </div>
            </div>

            <br />
            <div class="row">

                <div class="col-4">
                    <div class="form-group">
                        <label class="form-label">Hostel Address</label>
                        <input class="form-control" id="txtHostelAddress" type="text" readonly value="@Model.HostelAddress" placeholder="">
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label class="form-label">Home Address</label>
                        <input class="form-control" id="txtHomeAddress" type="text" value="@Model.HouseAddress" readonly placeholder="">
                    </div>
                </div>

                <div />
            </div>
            <br />
            <div class="row">
                <div class="col-4">
                    <div class="form-group">
                        <label class="form-label">Course of Study</label>
                        <input class="form-control" id="txtCourseOfStudy" value="@Model.CourseOfStudy" type="text" readonly placeholder="">
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label class="form-label">Faculty</label>
                        <input class="form-control" id="txtFaculty" type="text" value="@Model.Faculty" readonly placeholder="">
                    </div>
                </div>
                <div class="col-4">
                    <div class="form-group">
                        <label class="form-label">Ambition</label>
                        <input class="form-control" id="txtAmbition" type="text" value="@Model.Ambition" readonly placeholder="">
                    </div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-4">
                    <div class="form-group">
                        <label class="form-label">Social Media Address</label>
                        <input class="form-control" id="txtSocialMediaAddress" value="@Model.SocialMediaAddress" readonly type="text" placeholder="">
                    </div>
                </div>
            </div>
                <div class="row">
                <div class="col-lg-4">
                    <div class="form-group mg-b-10-force">
                        <label for="">Date Join ESM</label>
                        <div class="ate-input">
                            <div class="ate-input">
                                <input type="text" class="date form-control" placeholder="" value="@Model.strYearJoinESM" readonly id="txtDateJoinESM">
                            </div>
                        </div>
                    </div>
                </div><!-- col-4 -->
                <div class="col-lg-4">
                    <div class="form-group mg-b-10-force">
                        <label for="">Year Of Entry</label>
                        <div class="ate-input">
                            <div class="ate-input">
                                <input type="text" class="date form-control" placeholder="" value="@Model.strYearOfEntry" readonly id="txtYearOfEntry">
                            </div>
                        </div>
                    </div>
                </div><!-- col-4 -->
                <div class="col-lg-4">
                    <div class="form-group mg-b-10-force">
                        <label for="">Year Of Graduation</label>
                        <div class="ate-input">
                            <div class="ate-input">
                                <input type="text" class="date form-control" placeholder="" value="@Model.strYOG" readonly id="txtYearOfGraduation">
                            </div>
                        </div>
                    </div>
                </div><!-- col-4 -->
                <div class="col-lg-4">
                    <div class="form-group mg-b-10-force">
                        <label for="">Date Of Birth</label>
                        <div class="ate-input">
                            <div class="ate-input">
                                <input type="text" class="date form-control" placeholder="" value="@Model.strDateOfBirth" readonly id="txtDateOfBirth">
                            </div>
                        </div>
                    </div>
                </div><!-- col-4 -->
            </div>

            <div class="text-center">
                <br />
                <button class="btn btn-primary" type="submit" id="saveRecord">Save</button>
                <br />
            </div>
        </form>
    </div>
</div>

@section scripts{
    <script>

        $(document).ready(function () {
            $("#drpGender").val('@Model.Gender').trigger('change');
            $("#drpState").val('@Model.StateOfOrigin').trigger('change');
            $("#drpLga").val('@Model.LGA').trigger('change');

        });
        
    </script>
}