ESMIlWebApp/Controllers/Testimony/TestimonyViewController.cs
using DataStructure.ViewModel;
using Infrastructure.Interface;
using Infrastructure.Service;
using Microsoft.AspNetCore.Mvc;

namespace ESMIlWebApp.Controllers.Testimony
{
    public class TestimonyViewController : Controller
    {
        private readonly ITestimonyRepository testimony;

        public TestimonyViewController(ITestimonyRepository testimony) 
        {
        this.testimony = testimony;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        [Route("New/Testimony")]
        public IActionResult CreateNewTestimony() => View();
        [HttpGet]
        [Route("All/Testimony")]
        public IActionResult AllTestimony() => View();

        [Route("Update/Testimony")]
        public IActionResult UpdateTestimony()
        {
            var model = new TestimonyDTO();
            var rowId = Request.Form["updateRecordId"].FirstOrDefault();
            if (rowId == null)
            {
                ViewBag.NoRecordFound = "No record found";
                return View();
            }
            var id = int.Parse(rowId);
            model = testimony.ListAllTestimony().Where(s => s.Id == id).FirstOrDefault();

            return View(model);
        }
        [Route("View/Testimony")]
        public IActionResult ViewTestimony()
        {
            var model = new TestimonyDTO();
            var rowId = Request.Form["viewRecordId"].FirstOrDefault();
            if (rowId == null)
            {
                ViewBag.NoRecordFound = "No record found";
                return View();
            }
            var id = int.Parse(rowId);
            model = testimony.ListAllTestimony().Where(s => s.Id == id).FirstOrDefault();

            return View(model);
        }
    }
}

ESMIlWebApp/Views/TestimonyView/AllTestimony.cshtml
@{
    ViewData["Title"] = "Testimony";
    Layout = "~/Views/Shared/_layout.cshtml";
}

<style>

</style>

<button class="btn btn-primary btn-rounded" id="newRecord">Capture New Record</button>
<br>
<br>
<div class="container-fluid">
    <form>
        <div class="row">
            <div class="col-lg-4">
                <div class="form-group mg-b-10-force">
                    <label class="form-control-label">No Of Testimony To Display</label> 
                    <input id="rowId" type="hidden">
                    <vc:testimony-number-to-display></vc:testimony-number-to-display>
                </div>
            </div>
        </div><br>
        <div class="row-2">
            
            <button class="btn btn-primary" type="submit" id="saveRecord">Display</button>
        </div>
    </form>
</div><br>
<div class="table-responsive">
    <table id="testimonyTable" width="100%" class="stripe hover">
        <thead>
            <tr>
                <th>Actions</th>
                <th>ID</th>
                <th>Surname</th>
                <th>Firstname</th>
                <th>Department</th>
                <th>The Goodnews </th>
                <th>Testimony Date</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>



@using (Html.BeginForm("ViewTestimony", "TestimonyView", FormMethod.Post, new { id = "viewTestimonyForm", target = "_blank" }))
{
    <input type="hidden" name="viewRecordId" id="viewRecordId">
}
@using (Html.BeginForm("UpdateTestimony", "TestimonyView", FormMethod.Post, new { id = "updateTestimonyForm", target = "_blank" }))
{
    <input type="hidden" name="updateRecordId" id="updateRecordId">
}


@section scripts{
    <script>

        var table = $("#testimonyTable").DataTable({
            columnDefs: [{
                targets: [5],
                render: $.fn.dataTable.render.ellipsis(30)
            }],
            "lengthMenu": [[7, 20, 25, 50, -1], [7, 20, 25, 50, "All"]],
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "paginate": true,
            "scrollX": true,
            // colReorder: false,
            //  rowReorder:false,
            //select: true,
            //dom: 'Bfrtip', , new{area="Unit"}
            "ajax": {
                "url": "@Url.Action("GetAllTestimony","Testimony")",
                "type": "POST",
                "datatype": "json",
                "data": function (arg) { }
            },
            "columns": [
                {
                    "data": null, "name": "Action", "defaultContent": '<div class="btn-group mr-1 mb-1">' +
                        "<button aria-expanded='false' aria-haspopup='true' class='btn btn-white dropdown-toggle' data-toggle='dropdown' id='dropdownMenuDetail' type='button'></button>" +
                        "<div aria-labelledby='dropdownMenuButton6' class='dropdown-menu'>" +
                        "<a class='dropdown-item' href='#' id='changeRecord' title='Update record'><i class='fa fa-edit'></i>&nbsp; Update record</a>" +
                        "<a class='dropdown-item' href='#' id='viewRecord' title='View record'><i class='fa fa-info-circle'></i>&nbsp; View record</a>" +
                        "</div>" +
                        '</div>'

                },

                { "data": "id", "name": "id", "autoWidth": false },
                { "data": "surname", "name": "surname", "autoWidth": false },
                { "data": "firstname", "name": "firstname", "autoWidth": false },
                { "data": "department", "name": "department", "autoWidth": false },
                { "data": "theGoodNews", "name": "theGoodnews", "autoWidth": false },
                { "data": "strDate", "name": "strDate", "autoWidth": false }

            ],

        });




        $('#testimonyTable tbody').on('click', '#viewRecord', function (e) {
            e.preventDefault();
            var data = table.row($(this).parents('tr')).data();
            $("#viewRecordId").val(data.id);
            $("#viewTestimonyForm").submit();

        });

        $('#testimonyTable tbody').on('click', '#changeRecord', function (e) {
            e.preventDefault();
            var data = table.row($(this).parents('tr')).data();
            $("#updateRecordId").val(data.id);
            $("#updateTestimonyForm").submit();

        });

        $('#newRecord').on('click', function (e) {
            e.preventDefault();
            var returnUrl = '@Url.Action("CreateNewTestimony", "TestimonyView")';
            window.location.href = returnUrl;
        });

        $('#saveRecord').on('click', function(e)
        {
        e.preventDefault();
         var body={
                Id: $("#rowId").val() == "" ? 0 : $.trim($("#rowId").val()),
                Number: $("#drpTestimony").val(),
         }
            $.ajax({
                type: "POST",
                url: "@Url.Action("TestimonyNumber","Testimony")",
                dataType: "Json",
                data: { payload: JSON.stringify(body) },
                success: function (result) {
                    if (result.hasError == false) {
                        Swal.fire(result.message, '', 'success');
                       }
                    else if (result.hasError == true) {
                        Swal.fire(result.message, '', 'error');
                    }

                },

            });
        });

    </script>
   }

ESMIlWebApp/Views/TestimonyView/CreateNewTestimony.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4 class="text-muted"> Testimony</h4>
<h5 class="text-muted">Capture new record</h5>

<div class="container" style="background-color:lightblue">
    <form id="clearFrm" class="justify-content-center">
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label class="form-label">Surname</label>
                    <input id="rowId" type="hidden">
                    <input class="form-control" id="txtSurname" type="text" placeholder="">
                </div>

            </div>
            <div class="col-6">
                <div class="form-group">
                    <label class="form-label">Firstname</label>
                    <input class="form-control" id="txtFirstname" type="text" placeholder="">
                </div>
            </div>

        </div>
        <br />
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label class="form-control-label">Goodnews</label>
                    <input class="form-control" id="txtGoodnews" type="text" placeholder="">
                </div>
            </div>
                 
            <div class="col-6">
                <div class="form-group">
                    <label class="form-label">Department</label>
                    <input class="form-control" id="txtDepartment" type="text" placeholder="">
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-6 justify-content-center">
                <div class="form-group mg-b-10-force">
                    <label for="">Date </label>
                    <div class="ate-input">
                        <div class="ate-input">
                            <input type="text" class="date form-control" placeholder="Date" id="txtTestimonyDate">
                        </div>
                    </div>
                </div>
            </div><!-- col-4 -->
        </div>
        <br />
        
        
        <div class="text-center">
            <br />
            <button class="btn btn-primary" type="submit" id="saveRecord">Save</button>
        </div>
        <br />
    </form>
</div>


@section scripts{

    <script>

        var saveUrl = "@Url.Action("AddUpdateTestimomy","Testimony")";
        $.fn.clearForm = function () {
            this.each(function () { this.reset(); })
        }
        $("#saveRecord").click(function (e) {
            e.preventDefault();

            var body = {
                Id: $("#rowId").val() == "" ? 0 : $.trim($("#rowId").val()),
                Surname: $.trim($("#txtSurname").val()),
                Firstname: $.trim($("#txtFirstname").val()),
                TestimonyDate: $.trim($("#txtTestimonyDate").val()),
                Department: $.trim($("#txtDepartment").val()),
                TheGoodNews: $.trim($("#txtGoodnews").val())
            }

            $.ajax({
                type: "POST",
                url: saveUrl,
                dataType: "Json",
                data: { payload: JSON.stringify(body) },
                success: function (result) {
                    if (result.hasError == false) {
                        Swal.fire(result.message, '', 'success');
                        $("#clearFrm").each(function () {
                            this.reset();
                        })
                    }
                    else if (result.hasError == true) {
                        Swal.fire(result.message, '', 'error');
                    }

                },

            });
        });
        jQuery('.date').datepicker({
            timepicker: false,
            format: 'Y/d/m',
        });

    </script>
}

ESMIlWebApp/Views/TestimonyView/UpdateTestimony.cshtml
@model DataStructure.ViewModel.TestimonyDTO
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4 class="text-muted">Update Testimony</h4>

<div class="container" style="background-color:lightblue">
    <form id="clearFrm" class="justify-content-center">
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label class="form-label">Surname</label>
                    <input id="rowId" value="@Model.Id" type="hidden">
                    <input class="form-control" id="txtSurname" value="@Model.Surname" type="text" placeholder="">
                </div>

            </div>
            <div class="col-6">
                <div class="form-group">
                    <label class="form-label">Firstname</label>
                    <input class="form-control" id="txtFirstname" value="@Model.Firstname" type="text" placeholder="">
                </div>
            </div>

        </div>
        <br />
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label class="form-control-label">Goodnews</label>
                    <textarea class="form-control" id="txtGoodnews" type="text" placeholder="">@Model.TheGoodNews</textarea>
                </div>
            </div>

            <div class="col-6">
                <div class="form-group">
                    <label class="form-label">Department</label>
                    <input class="form-control" id="txtDepartment" type="text" value="@Model.Department" placeholder="">
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-6 justify-content-center">
                <div class="form-group mg-b-10-force">
                    <label for="">Date </label>
                    <div class="ate-input">
                        <div class="ate-input">
                            <input type="text" class="date form-control" placeholder="Date" value="@Model.strDate" id="txtTestimonyDate">
                        </div>
                    </div>
                </div>
            </div><!-- col-4 -->
        </div>
        <br />


        <div class="text-center">
            <br />
            <button class="btn btn-primary" type="submit" id="saveRecord">Save</button>
        </div>
        <br />
    </form>
</div>


@section scripts{

    <script>

        var saveUrl = "@Url.Action("AddUpdateTestimomy","Testimony")";
        $.fn.clearForm = function () {
            this.each(function () { this.reset(); })
        }
        $("#saveRecord").click(function (e) {
            e.preventDefault();

            var body = {
                Id: $("#rowId").val() == "" ? 0 : $.trim($("#rowId").val()),
                Surname: $.trim($("#txtSurname").val()),
                Firstname: $.trim($("#txtFirstname").val()),
                TestimonyDate: $.trim($("#txtTestimonyDate").val()),
                Department: $.trim($("#txtDepartment").val()),
                TheGoodNews: $.trim($("#txtGoodnews").val())
            }

            $.ajax({
                type: "POST",
                url: saveUrl,
                dataType: "Json",
                data: { payload: JSON.stringify(body) },
                success: function (result) {
                    if (result.hasError == false) {
                        Swal.fire(result.message, '', 'success');
                        $("#clearFrm").each(function () {
                            this.reset();
                        })
                    }
                    else if (result.hasError == true) {
                        Swal.fire(result.message, '', 'error');
                    }

                },

            });
        });
        jQuery('.date').datepicker({
            timepicker: false,
            format: 'Y/d/m',
        });

    </script>
}

ESMIlWebApp/Views/TestimonyView/ViewTestimony.cshtml
@model DataStructure.ViewModel.TestimonyDTO
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4 class="text-muted">View Testimony</h4>

<div class="container" style="background-color:lightblue">
    <form id="clearFrm" class="justify-content-center">
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label class="form-label">Surname</label>
                    <input id="rowId" value="@Model.Id" type="hidden">
                    <input class="form-control" id="txtSurname" value="@Model.Surname" readonly type="text" placeholder="">
                </div>

            </div>
            <div class="col-6">
                <div class="form-group">
                    <label class="form-label">Firstname</label>
                    <input class="form-control" id="txtFirstname" value="@Model.Firstname" readonly type="text" placeholder="">
                </div>
            </div>

        </div>
        <br />
        <div class="row">
            <div class="col-6">
                <div class="form-group">
                    <label class="form-control-label">Goodnews</label>
                    <textarea class="form-control" id="txtGoodnews" type="text" readonly placeholder="">@Model.TheGoodNews</textarea>
                </div>
            </div>

            <div class="col-6">
                <div class="form-group">
                    <label class="form-label">Department</label>
                    <input class="form-control" id="txtDepartment" type="text" readonly value="@Model.Department" placeholder="">
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-6 justify-content-center">
                <div class="form-group mg-b-10-force">
                    <label for="">Date </label>
                    <div class="ate-input">
                        <div class="ate-input">
                            <input type="text" class="date form-control" placeholder="Date" readonly value="@Model.strDate" id="txtTestimonyDate">
                        </div>
                    </div>
                </div>
            </div><!-- col-4 -->
        </div>
        <br />


    </form>
</div>