ESMIlWebApp/Controllers/ESMAF/ESMAFController.cs
using DataStructure.ViewModel;
using ESMIlWebApp.Ultilities;
using Infrastructure.Interface;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net;

namespace ESMIlWebApp.Controllers.ESMAF
{
    public class ESMAFController : Controller
    {
        private readonly IEsmafRepository _esmafQueryRepository;
        private readonly ILogger<GeneralMemberController> _logger;
        string errorMessage = string.Empty;
        public ESMAFController(ILogger<GeneralMemberController> logger, IEsmafRepository queryRepository)
        {
            _esmafQueryRepository = queryRepository;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> AddOrUpdateEsmaf(string payload)
        {

            try
            {
                if (payload != null)
                    payload = EncryptionExtensions.EncryptStringAES(payload);
                var payloadd = EncryptionExtensions.DecryptStringAES(payload);
                var model = JsonConvert.DeserializeObject<EsmafData>(payloadd);

                var saveEsmaf = await _esmafQueryRepository.AddOrUpdateESMAfAsync(model);
                if (model.Id > 0)
                {
                    return Json(new ResponseModel { message = $"{model.Surname}'s record successfully updated ", hasError = false, statusCode = (int)HttpStatusCode.OK });
                }
                return Json(new ResponseModel { message = $"{model.Surname} has been added successfully", hasError = false, statusCode = (int)HttpStatusCode.OK });
            }
            catch (Exception e)
            {

                _logger.LogError("Error", e);
                errorMessage = e.Message;
            }
            return Json(new ResponseModel { message = $"Error Message {Environment.NewLine}{errorMessage}", hasError = true, statusCode = (int)HttpStatusCode.BadRequest });
        }

        public IActionResult GetAllEsmaf()
        {
            string errorMessage;
            try
            {
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();

                var search = Request.Form["search[value]"].FirstOrDefault();

                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int totalRecord = 0;

                var esmafRecord = _esmafQueryRepository.ListAllEsmafAsync().ToList();

                if (!string.IsNullOrWhiteSpace(search.ToString()))
                {
                    esmafRecord = esmafRecord.Where(s => s.Surname.ToLower().Contains(search)
                      || s.Othernames.ToLower().Contains(search)
                      || s.PhoneNumber.ToLower().Contains(search)
                      || s.strngYearOfEntry.ToLower().Contains(search)
                      || s.strngYearOfGraduation.ToLower().Contains(search)
                      || s.Gender.ToLower().Contains(search)
                      || s.PhoneNumber.ToLower().Contains(search)
                      || s.Email.ToLower().Contains(search)
                      || s.CourseOfStudy.ToLower().Contains(search)).ToList();
                }
                totalRecord = esmafRecord.Count();
                esmafRecord = esmafRecord.OrderByDescending(s => s.Id).ToList();
                if (pageSize != -1)
                {
                    esmafRecord = esmafRecord.OrderByDescending(s => s.Id).Skip(skip).Take(pageSize).ToList();
                }
                return Json(new
                {
                    draw,
                    recordsFiltered = totalRecord,
                    recordsTotal = totalRecord,
                    data = esmafRecord
                });

            }
            catch (Exception e)
            {
                _logger.LogError("Error", e.Message);
                errorMessage = e.Message;
            }
            return Json(new ResponseModel {hasError = true, message = $" Error:\a {errorMessage}" });


        }

        public IActionResult GetAllPastExecutive() 
        {
            string errorMessage;
            try
            {
                var draw = Request.Form["draw"].FirstOrDefault();
                var start = Request.Form["start"].FirstOrDefault();
                var length = Request.Form["length"].FirstOrDefault();

                var search = Request.Form["search[value]"].FirstOrDefault();

                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int totalRecord = 0;

                var pastExecutiveRecord = _esmafQueryRepository.ListAllPastExecutive().ToList();

                if (!string.IsNullOrWhiteSpace(search.ToString()))
                {
                    pastExecutiveRecord = pastExecutiveRecord.Where(s => s.SurnameExcos.ToLower().Contains(search)
                      || s.OthernameExcos.ToLower().Contains(search)
                      || s.Phone.ToLower().Contains(search)
                      || s.Office.ToLower().Contains(search)
                      || s.Gender.ToLower().Contains(search)
                      || s.AcademicSectionDate.ToLower().Contains(search)
                      || s.Email.ToLower().Contains(search)).ToList();
                }
                totalRecord = pastExecutiveRecord.Count();
                pastExecutiveRecord = pastExecutiveRecord.OrderByDescending(s => s.Id).ToList();
                if (pageSize != -1)
                {
                    pastExecutiveRecord = pastExecutiveRecord.OrderByDescending(s => s.Id).Skip(skip).Take(pageSize).ToList();
                }
                return Json(new
                {
                    draw,
                    recordsFiltered = totalRecord,
                    recordsTotal = totalRecord,
                    data = pastExecutiveRecord
                });

            }
            catch (Exception e)
            {
                _logger.LogError("Error", e.Message);
                errorMessage = e.Message;
            }
            return Json(new ResponseModel {hasError = true, message = $" Error:\a {errorMessage}" });
        }

    }
}

ESMIlWebApp/Controllers/ESMAF/ESMAFDataViewController.cs
using Infrastructure.Interface;
using Microsoft.AspNetCore.Mvc;

namespace ESMIlWebApp.Controllers.Testimony
{
    public class ESMAFDataViewController : Controller
    {
        private readonly IEsmafRepository _esmafRepository;

        public ESMAFDataViewController(IEsmafRepository esmafRepository) 
        {
        this._esmafRepository = esmafRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        [Route("All/PastExecutive")]
        public IActionResult AllPastExecutive() => View();
    }
}

ESMIlWebApp/Views/ESMAFDataView/AllPastExecutive.cshtml
@{
    ViewData["Title"] = "Past Executive";
    Layout = "~/Views/Shared/_layout.cshtml";
}


<br>
<div class="table-responsive">
    <table id="pastExecutiveTable" width="100%" class="stripe hover">
        <thead>
            <tr>
                <th>Surname</th>
                <th>Othernames</th>
                <th>Gender</th>
                <th>Email</th>
                <th>Phone Number</th>
                <th>Office</th>
                <th>Academic Section</th>
                <th>Course of Study</th>
                <th>Faculty</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>



@using (Html.BeginForm("View", "View", FormMethod.Post, new { id = "viewTestimonyForm", target = "_blank" }))
{
    <input type="hidden" name="viewRecordId" id="viewRecordId">
}
@using (Html.BeginForm("Update", "TestimonyView", FormMethod.Post, new { id = "updateTestimonyForm", target = "_blank" }))
{
    <input type="hidden" name="updateRecordId" id="updateRecordId">
}


@section scripts{
    <script>

        var table = $("#pastExecutiveTable").DataTable({
            columnDefs: [{
               // targets: [5],
               // render: $.fn.dataTable.render.ellipsis(10)
            }],
            "lengthMenu": [[7, 20, 25, 50, -1], [7, 20, 25, 50, "All"]],
            "processing": true, // for show progress bar
            "serverSide": true, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "paginate": true,
            "scrollX": true,
            // colReorder: false,
            //  rowReorder:false,
            //select: true,
            //dom: 'Bfrtip', , new{area="Unit"}
            "ajax": {
                "url": "@Url.Action("GetAllPastExecutive","ESMAF")",
                "type": "POST",
                "datatype": "json",
                "data": function (arg) { }
            },
            "columns": [
                { "data": "surnameExcos", "name": "surnameExcos", "autoWidth": false },
                { "data": "othernameExcos", "name": "othernameExcos", "autoWidth": false },
                { "data": "gender", "name": "gender", "autoWidth": false },
                { "data": "email", "name": "email", "autoWidth": false },
                { "data": "phone", "name": "phone", "autoWidth": false },
                { "data": "office", "name": "office", "autoWidth": false },
                { "data": "academicSectionDate", "name": "academicSectionDate", "autoWidth": false },
                { "data": "department", "name": "department", "autoWidth": false },
                { "data": "faculty", "name": "faculty", "autoWidth": false }
            ],

        });




        $('#testimonyTable tbody').on('click', '#viewRecord', function (e) {
            e.preventDefault();
            var data = table.row($(this).parents('tr')).data();
            $("#viewRecordId").val(data.id);
            $("#viewTestimonyForm").submit();

        });

        $('#testimonyTable tbody').on('click', '#changeRecord', function (e) {
            e.preventDefault();
            var data = table.row($(this).parents('tr')).data();
            $("#updateRecordId").val(data.id);
            $("#updateTestimonyForm").submit();

        });

        $('#newRecord').on('click', function (e) {
            e.preventDefault();
            var returnUrl = '@Url.Action("CreateNewTestimony", "TestimonyView")';
            window.location.href = returnUrl;
        });

        $('#saveRecord').on('click', function (e) {
            e.preventDefault();
            var body = {
                Id: $("#rowId").val() == "" ? 0 : $.trim($("#rowId").val()),
                Number: $("#drpTestimony").val(),
            }
            $.ajax({
                type: "POST",
                url: "@Url.Action("","")",
                dataType: "Json",
                data: { payload: JSON.stringify(body) },
                success: function (result) {
                    if (result.hasError == false) {
                        Swal.fire(result.message, '', 'success');
                    }
                    else if (result.hasError == true) {
                        Swal.fire(result.message, '', 'error');
                    }

                },

            });
        });

    </script>
   }